modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/TwistedGate/OverEngineered/issues"
license="All rights reserved"

[[mods]]
	modId="overengineered"
	version="${file.jarVersion}"
	displayName="Over Engineered"
	displayURL="https://minecraft.curseforge.com/projects/overengineered"
	updateJSONURL="https://raw.githubusercontent.com/TwistedGate/OverEngineered/master/change.json"
	logoFile="oe_logo.png"
	credits=""
	authors="TwistedGate"
	description='''
This mod simply contains almost everything that i've wanted, but don't fit in anywhere else.

Random bits and bobs, here and there. Possibly containing QoL things.
'''

[[dependencies.overengineered]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[1.18.2-8.0.2-149,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.overengineered]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.25,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.overengineered]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2]"
	ordering="NONE"
	side="BOTH"
